spring.application.name=medical-clinic
spring.messages.basename=errors
spring.datasource.url=jdbc:postgresql://localhost:5432/medical_clinic_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true